---
title: Hello World!
author: Arindam Basu
date: '2017-11-04'
slug: hello-world
categories:
  - R
  - test
tags:
  - test
  - plot
---

## Setting up Hugo & RStudio with Netlify & Github: the story of this site



Standing in front of an ocean and counting the waves!

RStudio makes management of the blog on writing data analysis with github easy I'd say. Yihui Xie explains the details in the book [Blogdown](https://bookdown.org/yihui/blogdown/workflow.html) which you must read. Even then, you may end up and shoot a few troubles as I did. For a more graphical explanation, check out [Alison's Post](https://alison.rbind.io/post/up-and-running-with-blogdown/)

Assuming that you hava RStudio set up and configured, you will need to do the following:

## First, the eight-step process to get going on your machine

1. First, Install the blogdown package. 
2. Next, install [Hugo](http://gohugo.io) if you have not already installed it.
3. Edit the `~/.Rprofile` site as they detail in the [blogdown book](https://bookdown.org/yihui/blogdown/).
4. Then generate the site using `blogdown::new_site`
5. Write a post using the Addins dropdown menu from Rstudio. Most of the stuff should be ready for you to configure anyway, which is good. 
7. Click Serve Site to see the changes in a preview, but remember that when you will serve site you cannot work on the R console. It is locked.
8. Stop the server and restart R (In Mac, Cmd-shift-F10, or Session >> Restart R)
9. Then, do `blogdown::hugo_build()`; this will build the site for you and put all files in the public folder.

## Next, Blogdown book recommends we use Netlify for hosting and this is great. 

The best way to do is to get an account with Netlify and then connect a github repo to Netlify. But this is tricky. So, here are the lessons I learned.

1. Step 1, create a [github repo](http://www.github.com), remember to create an empty repo (do not add a readme file, do not add a .gitignore)
2. Step 2, assuming you have installed git, git into your repo from your folder where you have the files. You can use github's application appropriate for your operating system, or if you are in Mac:
 
 - First install git and then do:
 - cd into the folder where you have the site files
 - Issue the git commands:
 
 
```bash
 git init # initialise a git repo on your local machine
 git remote add origin <type the github repo url>
 git add . # caveat: bad practice, but do it this once
 git commit -m "my first commit" 
 # type your own message within quotes
 git push -u origin master 
 # push everything to the remote repo
```

 
 
Phew, if everything goes well, you will have a github repo with all the files and folders from your site. Now, go to step three

3. Step 3, you will connect your github repo to netlify. This is tricky, as Netlify only recognises hugo_0.19! I had a hard time in specifying hugo version 0.30 that I currently use and I had repeated build errors. Remember to put hugo_0.19 for build command, and public for the production folder. I found that adding "hugo" to buiild command in netlify does not work. 
4. Step 4, deploy. Netlify will provide you with a peculiar site name that you will need to reconfigure. 

I think the best thing would be to contact rbind.org folks and get an rbind.org sitename address if your aim is to work in data sciencey type of work or using it as a knowledgebase for Rstudio or R and data science. But you can change, as I changed the URL of this blog to:

[arinbasu-r.netlify.com](https://arinbasu-r.netlify.com)




